version: '3.5'

services:
  client:
    image: inventory-coop-client
    build:
      context: .
    ports:
    - 8080:80
    environment:
      NGINX_PORT: 80
    networks:
    - frontend

networks:
  frontend:
    external:
      name: inventory_coop_frontend